name: Initial Commit

on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: "*"
  pull_request:
    branches: [main]

jobs:
  init:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      repository-projects: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: andrehbui/looker-validation
          ref: v0.0.3
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./.github/actions/looker-validation
      - name: Check some stuff
        run: |
          cd .github/actions/looker-validation
          ls
      - name: Test run private action
        id: greetings
        uses: ./.github/actions/looker-validation/
        with:
          name: 'Goofus'
          branch: ${{ github.ref_name }}
          project: 'testing'
      - name: Test phrase
        run: |
          echo ${{ steps.greetings.outputs.phrase }}
      - name: Test project
        run: |
          echo ${{ steps.greetings.outputs.project }}
      - name: Test branch
        run: |
          echo ${{ steps.greetings.outputs.branch }}
